version: "3.9"

services:

  db:
    image: postgres:13.3
    container_name: qrescue-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=qrescue
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - D:\Volumes:/var/lib/postgresql/data
    restart: always

  app:
    platform: linux/amd64
    container_name: app-rescue
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE-HOST-ENV=db:5432
      - DATABASE-NAME-ENV=qrescue
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    restart: always
volumes:
  pgdata:
