CREATE TABLE osbb(
                     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     login varchar(100) NOT NULL,
                     password varchar(100) NOT NULL
);

CREATE TABLE head_osbb(
                          id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          name varchar(100),
                          lastname varchar(100),
                          phone varchar(13),
                          email varchar(100),
                          id_osbb int REFERENCES osbb(id) ON DELETE CASCADE
);

CREATE TABLE data(
                     id int PRIMARY KEY REFERENCES osbb(id) ON DELETE CASCADE,
                     address varchar
);

CREATE OR REPLACE FUNCTION create_head_osbb_data()
RETURNS TRIGGER AS $$
BEGIN
INSERT INTO head_osbb (id_osbb) VALUES (NEW.id);
INSERT INTO data (id) VALUES (NEW.id);
RETURN NEW;
END;

$$ LANGUAGE plpgsql;

CREATE TRIGGER osbb_after_insert
    AFTER INSERT ON osbb
    FOR EACH ROW
    EXECUTE FUNCTION create_head_osbb_data();